sonar.projectKey=s226084301-boop_8.2CDevSecOps
sonar.organization=s226084301-boop
sonar.host.url=https://sonarcloud.io
sonar.token=${SONAR_TOKEN}
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8
